# Subsetting data
1) Selecting(Columns)
2)Slicing (Rows)
3)Indexing (Selecting +Slicing)- through loc and iloc
4)Filtering (Selecting based on criteria)

In [44]:
## WORKING WITH DIRECTORIES
import os
os.getcwd()
os.chdir('C:\Users\DELL\Desktop')

'C:\\Users\\DELL'

In [20]:
import pandas as pd
import numpy as np

In [21]:
data=pd.read_csv(r"C:\Users\DELL\Desktop\EMERGING WOMEN\AB_NYC_2019.csv\AB_NYC_2019.csv")

In [5]:
data.sample(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
30316,23435040,1 bd Apartment next to Subway,57292550,Elle,Brooklyn,Sheepshead Bay,40.58591,-73.95099,Entire home/apt,70,2,1,2018-02-27,0.06,1,0
9152,7003788,Luxury Apt 10mins Manhattan,21773199,Joo,Queens,Long Island City,40.74406,-73.94504,Entire home/apt,149,4,4,2015-10-17,0.09,1,0
42649,33110303,Cozy NYC Studio with Great Light & Comfort!,11776513,Yuki,Manhattan,Upper East Side,40.78475,-73.95339,Entire home/apt,99,10,2,2019-05-02,0.59,1,188
40651,31533898,TRENDi 6 BEDROOM 2 APARTMENTS COMBINED/12 BEDS,133234099,Gemma,Manhattan,Harlem,40.80950,-73.94297,Entire home/apt,750,3,0,NaN,NaN,2,97
32692,25745458,Huge and beautiful 2BR in Greenpoint Brooklyn,2483350,Avital,Brooklyn,Greenpoint,40.73503,-73.95470,Entire home/apt,114,10,1,2019-02-07,0.20,1,0
17865,13997894,1 bedroom full apartment completely private!,83616984,Horacio,Queens,Corona,40.74598,-73.85683,Entire home/apt,85,7,60,2019-06-30,1.65,1,284
8043,6198343,Calm airy top floor W'burgh 1.5 bed,1245722,Jen,Brooklyn,Williamsburg,40.71776,-73.94538,Entire home/apt,200,3,30,2019-07-01,0.65,1,364
37833,29946107,"Spacious, sun-filled apartment in family townhome",3662048,Daphne,Brooklyn,Carroll Gardens,40.67948,-73.99531,Entire home/apt,147,6,14,2019-06-21,1.84,1,14
45544,34817032,Fantastic Midtown Elegance,94101463,Jessica,Manhattan,Midtown,40.75316,-73.97099,Entire home/apt,300,3,15,2019-07-06,8.82,1,357
31012,24042332,Beautiful sunlit spacious loft-like pvt. bedroom!,56917612,Jason,Brooklyn,Bushwick,40.69781,-73.92093,Private room,60,1,16,2019-07-06,1.20,1,21

In [10]:
data[data.price.between(10,20)]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
957,375249,Enjoy Staten Island Hospitality,1887999,Rimma & Jim,Staten Island,Graniteville,40.62109,-74.16534,Private room,20,3,80,2019-05-26,0.92,1,226
2860,1620248,Large furnished 2 bedrooms- - 30 days Minimum,2196224,Sally,Manhattan,East Village,40.73051,-73.98140,Entire home/apt,10,30,0,NaN,NaN,4,137
3950,2459916,"$455 Cozy 1bd, BKLYN Sublet March",12577771,Victor,Brooklyn,Bedford-Stuyvesant,40.68948,-73.93528,Private room,18,1,0,NaN,NaN,1,0
4647,3258197,Large 1br Duplex in Heart of Upper East Side,16477306,Jeff,Manhattan,Upper East Side,40.76866,-73.95553,Entire home/apt,16,2,21,2019-06-30,1.69,1,9
5542,4031809,Prewar classic NYC apartment.,20902552,Miquel,Manhattan,Washington Heights,40.83456,-73.94344,Private room,16,14,0,NaN,NaN,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47160,35612982,Luggage drop off ONLY! Close to LGA & JFK,108512889,Syed,Queens,Sunnyside,40.73954,-73.92095,Shared room,12,1,0,NaN,NaN,1,359
47218,35642891,Beautiful room in Bushwick,268138154,Julio,Brooklyn,Bushwick,40.69640,-73.91898,Private room,10,1,2,2019-06-18,2.00,1,0
47979,36022650,Charming entire apartment in Hell's Kitchen,2967377,Aude,Manhattan,Hell's Kitchen,40.76279,-73.99463,Entire home/apt,15,2,0,NaN,NaN,1,139
48486,36280646,"Cable and wfi, L/G included.",272872092,Chris,Queens,Forest Hills,40.73657,-73.85088,Entire home/apt,16,9,1,2019-07-07,1.00,1,322
48832,36450814,FLATBUSH HANG OUT AND GO,267223765,Jarmel,Brooklyn,Flatbush,40.64922,-73.96078,Shared room,20,1,0,NaN,NaN,3,363

In [11]:
data[data.price.isin(10,12,15,20)]

TypeError: isin() takes 2 positional arguments but 5 were given

In [24]:
##Indexing (selecting +slicing)
data.id
data['id']
data[['id','name','neighbourhood']]
data.loc[[1,2,3,4,5,6,7],['id','name']]
data.iloc[[1,2,3,10],[0,1,5]]

      id                                 name    neighbourhood
1   2595                Skylit Midtown Castle          Midtown
2   3647  THE VILLAGE OF HARLEM....NEW YORK !           Harlem
3   3831      Cozy Entire Floor of Brownstone     Clinton Hill
10  5295     Beautiful 1br on Upper West Side  Upper West Side

In [33]:
##Filtering
data.query("price >80")
data[data.reviews_per_month.isna()]
data[~data.reviews_per_month.isna()]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
5,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48782,36425863,Lovely Privet Bedroom with Privet Restroom,83554966,Rusaa,Manhattan,Upper East Side,40.78099,-73.95366,Private room,129,1,1,2019-07-07,1.00,1,147
48790,36427429,No.2 with queen size bed,257683179,H Ai,Queens,Flushing,40.75104,-73.81459,Private room,45,1,1,2019-07-07,1.00,6,339
48799,36438336,Seas The Moment,211644523,Ben,Staten Island,Great Kills,40.54179,-74.14275,Private room,235,1,1,2019-07-07,1.00,1,87
48805,36442252,1B-1B apartment near by Metro,273841667,Blaine,Bronx,Mott Haven,40.80787,-73.92400,Entire home/apt,100,1,2,2019-07-07,2.00,1,40
48852,36455809,"Cozy Private Room in Bushwick, Brooklyn",74162901,Christine,Brooklyn,Bushwick,40.69805,-73.92801,Private room,30,1,1,2019-07-08,1.00,1,1

In [41]:
#String filtering - IMP
#substring filtering using startswith, endswith and contains
#data[data.neighbourhood_group.str.contains("Manhattan")]
#data[data.neighbourhood_group.str.startswith("Brook")]
data[data.host_name.isin(['Jennifer','Laura'])]
#data[data.host_name.str.istitle()]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
48,13050,bright and stylish duplex,50846,Jennifer,Brooklyn,Bedford-Stuyvesant,40.68554,-73.94090,Entire home/apt,115,3,11,2017-01-01,0.10,1,0
306,71248,Bright and lovely 1 bdrm apt in LES,363834,Jennifer,Manhattan,Chinatown,40.71659,-73.98945,Entire home/apt,125,25,43,2019-06-17,0.42,1,102
326,80493,Cozy room in East Village with AC,434987,Jennifer,Manhattan,East Village,40.72329,-73.98486,Private room,71,2,182,2019-07-04,1.81,1,200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48144,36108534,Luxury 1 bed in UWS Finest Building with Gym #...,116305897,Laura,Manhattan,Upper West Side,40.78935,-73.97389,Entire home/apt,180,30,0,NaN,NaN,9,311
48155,36109805,Amazing Studio in the UWS with Gym #6108,116305897,Laura,Manhattan,Upper West Side,40.79098,-73.97384,Entire home/apt,150,30,0,NaN,NaN,9,343
48164,36113257,WaHi Walk Up,22528598,Jennifer,Manhattan,Washington Heights,40.85269,-73.93616,Private room,80,1,1,2019-06-29,1.00,1,68
48511,36304817,HugeHipHome 5BR 2 Bath w/ Yard 15 min to Midtown!,143725634,Jennifer,Queens,Long Island City,40.76001,-73.93031,Entire home/apt,450,2,0,NaN,NaN,1,321
48853,36455917,Sunny&quiet paradise in the WV with open views,274103383,Jennifer,Manhattan,West Village,40.73444,-74.00335,Private room,202,2,0,NaN,NaN,1,84

In [11]:
#order by equivalent of SQL
data_order=data.sort_values('host_id',ascending='False')
data_order.head(100)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
30604,23669201,Great Price: Williamsburg Brooklyn Loft off L ...,2438,Tasos,Brooklyn,Williamsburg,40.71412,-73.94447,Entire home/apt,95,45,1,2018-03-17,0.06,1,0
2290,1101224,THE PUTNAM,2571,Teedo,Brooklyn,Bedford-Stuyvesant,40.68674,-73.93845,Entire home/apt,182,9,27,2019-05-21,0.37,1,23
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
13963,10593675,"La Spezia room. Clean, quiet and comfortable bed",2787,John,Brooklyn,Bensonhurst,40.60951,-73.97642,Shared room,79,1,15,2018-09-29,0.43,6,180
13583,10160215,Torre del Lago Room.,2787,John,Brooklyn,Gravesend,40.60755,-73.97410,Private room,79,1,17,2019-06-26,0.40,6,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,7750,Huge 2 BR Upper East Cental Park,17985,Sing,Manhattan,East Harlem,40.79685,-73.94872,Entire home/apt,190,7,0,NaN,NaN,2,249
3315,1980179,Best of the East Village Cozy 2 Bedroom,18174,Katya,Manhattan,East Village,40.72862,-73.98885,Entire home/apt,142,1,214,2019-07-05,3.17,1,242
12978,9855876,Large Room in LES ($80-100/night),18282,Daniel,Manhattan,Lower East Side,40.71813,-73.98715,Private room,70,1,3,2017-01-22,0.07,1,0
26553,21135737,Clean Comfortable Apartment near the Subway!,18283,Dominic,Brooklyn,Greenpoint,40.73222,-73.95395,Entire home/apt,150,3,0,NaN,NaN,1,0
16413,13182297,Sculptor's Light-filled Loft (Bushwick),18742,Serra Victoria,Brooklyn,Bushwick,40.70430,-73.92491,Entire home/apt,117,7,0,NaN,NaN,1,0

## Dataframe Info

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [13]:
data.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [14]:
data.sample(30)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
17695,13895437,Bushwick Basement Large Room with Half Bath,2776152,Jessica,Brooklyn,Bushwick,40.69904,-73.91792,Private room,38,1,3,2016-09-19,0.08,1,0
46099,35079012,Amazing Williamsburg Apartment,1722490,Dom,Brooklyn,Williamsburg,40.72096,-73.95528,Entire home/apt,150,5,0,NaN,NaN,1,0
36886,29320258,Private Room in Prime Bushwick,89339003,Shoshi,Brooklyn,Bushwick,40.70270,-73.91429,Private room,70,5,1,2019-02-17,0.21,1,53
40747,31626307,Bright and Airy Freeman Street loft,513839,Syed,Brooklyn,Greenpoint,40.73444,-73.95658,Entire home/apt,120,30,3,2019-05-14,0.53,1,209
48428,36262925,Amazing 1BR Apartment near Columbia University,6186588,Julio,Manhattan,Morningside Heights,40.81546,-73.95823,Entire home/apt,150,2,0,NaN,NaN,1,10
45931,35004930,Furnished Apartment in Queens,236530772,Maria,Queens,Jamaica Estates,40.72101,-73.79395,Entire home/apt,75,7,1,2019-06-07,0.91,2,14
111,26520,"Cozy Room #3, Landmark Home 1 Block to PRATT",51038,Erica,Brooklyn,Clinton Hill,40.68698,-73.96572,Private room,125,2,19,2019-06-02,0.20,6,250
17336,13686914,Murray Hill/Midtown East Flex Bedroom,28250527,Elisa,Manhattan,Midtown,40.75257,-73.97148,Private room,65,1,0,NaN,NaN,1,0
34195,27127722,Suite 18 - Cozy room w/ Private Bathroom,99296570,Daisy,Brooklyn,Brighton Beach,40.57987,-73.95889,Private room,65,1,43,2019-05-27,3.82,5,283
36203,28784880,*PRIVATE* Loft 5 minutes away from LaGuardia,65671256,Freddy,Queens,Jackson Heights,40.75703,-73.85827,Entire home/apt,72,1,70,2019-06-24,7.42,3,98
26005,20760187,Warm Duplex in a Brownstone,9663247,Roland,Brooklyn,Bedford-Stuyvesant,40.68371,-73.94050,Entire home/apt,160,3,20,2019-06-05,0.94,1,136
45838,34974562,Stylish Studios near Central Park,263505830,Elizabeth,Manhattan,Upper West Side,40.77927,-73.97649,Private room,100,28,0,NaN,NaN,1,166
31076,24118031,✔ Home Away From Home ✔ 100Mbps ✔ Transit Scor...,4924711,Daniel Rusteen,Bronx,Concourse,40.81952,-73.92844,Entire home/apt,95,2,37,2019-07-06,2.89,1,193
16545,13250484,Beautiful 2000 sq. ft. loft in Hells Kitchen NYC,10196579,James,Manhattan,Hell's Kitchen,40.75647,-73.99848,Entire home/apt,2000,1,4,2017-01-06,0.11,1,362
7035,5058683,It's always sunny in Williamsburg!,3074904,Lauren & Chelsea,Brooklyn,Williamsburg,40.71301,-73.95374,Private room,96,1,175,2019-06-16,3.27,4,44
26304,20970017,The Real B&B Home,89715420,J. Beverly,Brooklyn,Canarsie,40.64399,-73.89315,Entire home/apt,85,7,11,2018-09-22,0.64,1,1
11314,8783567,Studio Apt on The Upper West Side,46039971,Brady,Manhattan,Upper West Side,40.77874,-73.98437,Entire home/apt,190,5,15,2019-03-21,0.35,1,0
40321,31269703,Heart of Jamaica Queens,81146418,Monique,Queens,Jamaica,40.68684,-73.79921,Entire home/apt,80,2,13,2019-06-15,2.36,1,87
32487,25464886,Shared Cozy Apartment By Times Square Manhattan,187975743,R.Henry,Manhattan,Hell's Kitchen,40.76418,-73.98822,Shared room,99,1,42,2019-06-23,3.12,8,181
24322,19586663,Brooklyn's Big Room Next to Prospect Park,137673701,Brama,Brooklyn,Windsor Terrace,40.65963,-73.98068,Private room,45,7,1,2017-08-09,0.04,1,0
46812,35456622,4 Bedroom apartment in 2 family house in Broo...,266749340,Venessa,Brooklyn,Bedford-Stuyvesant,40.68919,-73.92553,Entire home/apt,190,1,3,2019-07-01,3.00,2,269
46284,35184104,Bedroom in Penthouse Apartment,49132405,Abshan,Manhattan,East Harlem,40.79908,-73.93291,Private room,140,2,1,2019-06-10,1.00,1,21
1778,799900,"Amazing apartment near museum, gardens & park!",4211266,Nora,Brooklyn,Prospect Heights,40.67338,-73.96415,Entire home/apt,150,17,3,2016-09-26,0.07,1,0
39335,30691956,Modern Room in LuxuryApt overlooking LIC&Manha...,100554481,Drew,Queens,Long Island City,40.74900,-73.94161,Private room,68,30,6,2019-05-24,1.04,1,0
32363,25325029,Bushwick Room with a View,24327574,Shadi,Brooklyn,Bushwick,40.69928,-73.92386,Private room,150,2,20,2018-10-22,1.52,1,0
12899,9821408,Cozy East Village apartment w Steinway piano,1010435,Carol,Manhattan,East Village,40.72792,-73.98718,Entire home/apt,125,7,4,2019-04-22,0.17,1,1
5768,4204988,Charming Soho One Bedroom + Loft,1162642,Emily,Manhattan,NoHo,40.72577,-73.99337,Entire home/apt,350,2,0,NaN,NaN,2,0
4604,3218320,SOHO Studio Best Location,3321910,Carl,Manhattan,Nolita,40.72243,-73.99655,Private room,125,6,3,2015-07-11,0.05,1,43
7824,5958299,Cozy NYC Bedroom in the Best Manhattan Location!,30454464,Sterling,Manhattan,Chelsea,40.74717,-73.99179,Private room,105,1,158,2019-07-04,3.08,1,105
46351,35217858,"comfortable, clean, sweet, conveniently located",41471153,Rina,Queens,Long Island City,40.76460,-73.93085,Private room,58,2,0,NaN,NaN,1,133

In [15]:
#data.T

,0,1,2,3,4,5,6,7,8,9,...,48885,48886,48887,48888,48889,48890,48891,48892,48893,48894
id,2539,2595,3647,3831,5022,5099,5121,5178,5203,5238,...,36482809,36483010,36483152,36484087,36484363,36484665,36485057,36485431,36485609,36487245
name,Clean & quiet apt home by the park,Skylit Midtown Castle,THE VILLAGE OF HARLEM....NEW YORK !,Cozy Entire Floor of Brownstone,Entire Apt: Spacious Studio/Loft by central park,Large Cozy 1 BR Apartment In Midtown East,BlissArtsSpace!,Large Furnished Room Near B'way,Cozy Clean Guest Room - Family Apt,Cute & Cozy Lower East Side 1 bdrm,...,Stunning Bedroom NYC! Walking to Central Park!!,Comfy 1 Bedroom in Midtown East,Garden Jewel Apartment in Williamsburg New York,"Spacious Room w/ Private Rooftop, Central loca...",QUIT PRIVATE HOUSE,Charming one bedroom - newly renovated rowhouse,Affordable room in Bushwick/East Williamsburg,Sunny Studio at Historical Neighborhood,43rd St. Time Square-cozy single bed,Trendy duplex in the very heart of Hell's Kitchen
host_id,2787,2845,4632,4869,7192,7322,7356,8967,7490,7549,...,131529729,274311461,208514239,274321313,107716952,8232441,6570630,23492952,30985759,68119814
host_name,John,Jennifer,Elisabeth,LisaRoxanne,Laura,Chris,Garon,Shunichi,MaryEllen,Ben,...,Kendall,Scott,Melki,Kat,Michael,Sabrina,Marisol,Ilgar & Aysel,Taz,Christophe
neighbourhood_group,Brooklyn,Manhattan,Manhattan,Brooklyn,Manhattan,Manhattan,Brooklyn,Manhattan,Manhattan,Manhattan,...,Manhattan,Manhattan,Brooklyn,Manhattan,Queens,Brooklyn,Brooklyn,Manhattan,Manhattan,Manhattan
neighbourhood,Kensington,Midtown,Harlem,Clinton Hill,East Harlem,Murray Hill,Bedford-Stuyvesant,Hell's Kitchen,Upper West Side,Chinatown,...,East Harlem,Midtown,Williamsburg,Hell's Kitchen,Jamaica,Bedford-Stuyvesant,Bushwick,Harlem,Hell's Kitchen,Hell's Kitchen
latitude,40.6475,40.7536,40.809,40.6851,40.7985,40.7477,40.6869,40.7649,40.8018,40.7134,...,40.7963,40.7556,40.7123,40.7639,40.6914,40.6785,40.7018,40.8147,40.7575,40.764
longitude,-73.9724,-73.9838,-73.9419,-73.9598,-73.944,-73.975,-73.956,-73.9849,-73.9672,-73.9904,...,-73.936,-73.9672,-73.9422,-73.9918,-73.8084,-73.95,-73.9332,-73.9487,-73.9911,-73.9893
room_type,Private room,Entire home/apt,Private room,Entire home/apt,Entire home/apt,Entire home/apt,Private room,Private room,Private room,Entire home/apt,...,Private room,Entire home/apt,Entire home/apt,Private room,Private room,Private room,Private room,Entire home/apt,Shared room,Private room
price,149,225,150,89,80,200,60,79,79,150,...,75,200,170,125,65,70,40,115,55,90
minimum_nights,1,1,3,1,10,3,45,2,2,1,...,2,6,1,4,1,2,4,10,1,7
number_of_reviews,9,45,0,270,9,74,49,430,118,160,...,0,0,0,0,0,0,0,0,0,0
last_review,2018-10-19,2019-05-21,NaN,2019-07-05,2018-11-19,2019-06-22,2017-10-05,2019-06-24,2017-07-21,2019-06-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reviews_per_month,0.21,0.38,NaN,4.64,0.1,0.59,0.4,3.47,0.99,1.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
calculated_host_listings_count,6,2,1,1,1,1,1,1,1,4,...,2,1,3,1,2,2,2,1,6,1
availability_365,365,355,365,194,0,129,0,220,0,188,...,353,176,365,31,163,9,36,27,2,23

In [17]:
data.shape

(48895, 16)

In [18]:
len(data)

48895

In [22]:
data.mean()
data.std()

id                                1.098311e+07
host_id                           7.861097e+07
latitude                          5.453008e-02
longitude                         4.615674e-02
price                             2.401542e+02
minimum_nights                    2.051055e+01
number_of_reviews                 4.455058e+01
reviews_per_month                 1.680442e+00
calculated_host_listings_count    3.295252e+01
availability_365                  1.316223e+02
dtype: float64

In [23]:
data.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [24]:
data.room_type.unique()

array(['Private room', 'Entire home/apt', 'Shared room'], dtype=object)

In [25]:
data.room_type.nunique()

3

In [27]:
data.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [28]:
data.index

RangeIndex(start=0, stop=48895, step=1)

In [31]:
data.iloc[1,:]

id                                                 2595
name                              Skylit Midtown Castle
host_id                                            2845
host_name                                      Jennifer
neighbourhood_group                           Manhattan
neighbourhood                                   Midtown
latitude                                        40.7536
longitude                                      -73.9838
room_type                               Entire home/apt
price                                               225
minimum_nights                                        1
number_of_reviews                                    45
last_review                                  2019-05-21
reviews_per_month                                  0.38
calculated_host_listings_count                        2
availability_365                                    355
Name: 1, dtype: object